# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Meta Information Key to Every Element of List
#' 
#' Description follows.
#' 
#'  @param x un-nested list
#'  @param y character vector of the same length as x
#'
add_key_to_listed_obj <- function(x, y) {
    .Call('miro_add_key_to_listed_obj', PACKAGE = 'miro', x, y)
}

